# Generated by Django 5.0.3 on 2024-04-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='optimization_district',
        ),
    ]
