# Generated by Django 5.0.3 on 2024-04-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_district_optimization_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='edited_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
