# Generated by Django 5.0.3 on 2024-04-09 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_district_edited_at'),
        ('timesheets', '0002_period_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_projects', to='timesheets.project'),
        ),
    ]
