# Generated by Django 5.0.3 on 2024-04-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_projects'),
        ('timesheets', '0003_remove_timesheet_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='projects',
        ),
        migrations.AddField(
            model_name='staff',
            name='projects',
            field=models.ManyToManyField(related_name='staff_projects', to='timesheets.project'),
        ),
    ]
