# Generated by Django 5.0.3 on 2024-05-20 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_department_lead'),
        ('timesheets', '0008_alter_period_total_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_type',
        ),
        migrations.AddField(
            model_name='staff',
            name='employee_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_district', to='staff.district'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='staff_projects', to='timesheets.project'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], default='ACTIVE', max_length=200, null=True),
        ),
    ]
