# Generated by Django 5.0.3 on 2024-05-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_remove_staff_staff_type_staff_employee_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
