# Generated by Django 5.0.3 on 2024-12-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_staff_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='hr_approval',
            field=models.BooleanField(default=False),
        ),
    ]
