# Generated by Django 5.1.8 on 2025-04-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_staff_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='projects',
        ),
    ]
