# Generated by Django 5.1.8 on 2025-04-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_remove_staff_projects'),
        ('timesheets', '0011_alter_timesheet_period_activity_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='project_activities',
            field=models.ManyToManyField(blank=True, related_name='staff_activity_projects', to='timesheets.activity'),
        ),
    ]
