# Generated by Django 5.0.3 on 2024-04-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_alter_period_status_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='edited_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
