# Generated by Django 5.0.3 on 2024-04-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_timesheet_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='first_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='rejected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='second_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
