# Generated by Django 5.0.3 on 2024-05-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_alter_project_edited_at_alter_timesheet_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='total_days',
            field=models.IntegerField(editable=False),
        ),
    ]
