# Generated by Django 5.0.3 on 2024-05-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0007_alter_period_total_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5),
        ),
    ]
