# Generated by Django 5.0.3 on 2024-12-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0008_alter_period_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='department_approver',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
