# Generated by Django 5.1.6 on 2025-04-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0011_alter_timesheet_period_activity_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='current_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Line Manager Approved', 'Line Manager Approved'), ('HR Approved', 'HR Approved'), ('Rejected', 'Rejected')], max_length=50),
        ),
    ]
