# Generated by Django 5.1.6 on 2025-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0012_alter_timesheet_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='actions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
